# Generated by Django 3.1 on 2020-08-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
